bin: some fixes; feature changes

diff --git a/_general/dot-local/bin/archive b/_general/dot-local/bin/archive
--- a/_general/dot-local/bin/archive
+++ b/_general/dot-local/bin/archive
@@ -1,71 +1,132 @@
 #!/bin/bash
 
-destination=
-sources=()
+# 1 exit code
+help() {
+	printf 'Usage: %s DESTINATION SOURCE...\n' "$(basename "$0")"
+	exit ${1:-1}
+}
+
+
+arg_destination=
+arg_sources=()
 
 main() {
 	parse_args "$@"
-
-	# Try to be smart and avoid multiple tar levels
-	if [ ${#sources[@]} -eq 1 ]
-	then
-		case "${sources[1]}" in
-			*.tar)
-				archive_single_tar "$destination" "${sources[1]}"
-				return
-				;;
-			*) ;;
-		esac
-	fi
-
-	archive_all "$destination" "${sources[@]}"
+	archive_all "$arg_destination" "${arg_sources[@]}"
 }
 
+# 1... sources
+source_is_tar() {
+	[ $# -ne 1 ] &&
+		return 1
+
+	case "$1" in
+		*.tar) ;;
+		*) return 1 ;;
+	esac
+
+	return 0
+}
+
+# 1... args
 parse_args() {
 	if [ $# -lt 2 ]; then
-		printf 'Usage: %s DESTINATION SOURCE...\n' "$(basename "$0")"
-		exit 1
+		help
 	fi
 
-	destination=$1
-	shift
-
-	sources=( "$@" )
+	arg_destination="$1"
+	arg_sources=( "${@:2}" )
 }
 
-archive_single_tar() {
-	dst=$1
-	src=$2
-	case "$dst" in
-		*.tar.gz|*.tgz           ) gzip  -c "$src" > "$dst" ;;
-		*.tar.bz2|*.tbz2|*.tbz   ) bzip2 -c "$src" > "$dst" ;;
-		*.tar.xz|*.txz           ) xz    -c "$src" > "$dst" ;;
-		*.tar.zma|*.tlz          ) lzma  -c "$src" > "$dst" ;;
 
-		* ) return 1;;
-	esac
-}
-
+# 1 destination
+# 2... sources
 archive_all() {
-	dst=$1
-	srcs=( ${@:1} )
+	archive="$1"
+	sources=( "${@:2}" )
 
-	case "$dst" in
-		*.tar                   ) tar -cvf        "$dst" "${src[@]}" ;;
-		*.tar.gz|*.tgz          ) tar -zcvf       "$dst" "${src[@]}" ;;
-		*.tar.bz2|*.tbz2|*.tbz  ) tar -jcvf       "$dst" "${src[@]}" ;;
-		*.tar.xz|*.txz          ) tar -Jcvf       "$dst" "${src[@]}" ;;
-		*.tar.zma|*.tlz         ) tar --lzma -cvf "$dst" "${src[@]}" ;;
-		*.gz                    ) gzip     --keep        "${src[@]}" ;;
-		*.bz2                   ) bzip2    --keep        "${src[@]}" ;;
-		*.xz                    ) xz       --keep        "${src[@]}" ;;
-		*.lzma                  ) lzma     --keep        "${src[@]}" ;;
-		*.zip                   ) zip -r          "$dst" "${src[@]}" ;;
-		*.7z                    ) 7z a -t7z       "$dst" "${src[@]}" ;;
+	# TODO: Omit specifying commands twice, to prevent nesting tar.
 
-		* ) printf "unsupported archive for '%s'\n" "$dst" >&2 ;;
+	case "$archive" in
+		*.tar)
+			tar --create --file="$archive" -- "${sources[@]}"
+			;;
+		*.tar.gz|*.tgz)
+			if source_is_tar "${sources[@]}"
+			then gzip --stdout --force --quiet -- "$source" > "$archive"
+			else tar --gzip --create --file="$archive" -- "${sources[@]}"
+			fi
+			;;
+		*.gz)
+			if [ ${#sources[@]} -gt 1 ]
+			then die "unable to compress multiple files in one gzip-archive"
+			else gzip --stdout --force --quiet -- "$source" > "$archive"
+			fi
+			;;
+		*.tar.bz2|*.tbz2|*.tbz)
+			if source_is_tar "${sources[@]}"
+			then bzip2 --stdout --force --quiet -- "$source" > "$archive"
+			else tar --bzip2 --create --file="$archive" -- "${sources[@]}"
+			fi
+			;;
+		*.bz2)
+			if [ ${#sources[@]} -gt 1 ]
+			then die "unable to compress multiple files as one bzip2-archive"
+			else bzip2 --stdout --force --quiet -- "$source" > "$archive"
+			fi
+			;;
+		*.tar.xz|*.txz)
+			if source_is_tar "${sources[@]}"
+			then xz --stdout --force --quiet -- "${sources[@]}" > "$archive"
+			else tar --xz --create --file="$archive" -- "${sources[@]}"
+			fi
+			;;
+		*.xz)
+			if [ ${#sources[@]} -gt 1 ]
+			then die "unable to compress multiple files in one xz-archive"
+			else xz --stdout --force --quiet -- "${sources[@]}" > "$archive"
+			fi
+			;;
+		*.tar.lzma|*.tlz)
+			if source_is_tar "${sources[@]}"
+			then lzma --stdout --force --quiet -- "${sources[@]}" > "$archive"
+			else tar --lzma --create --file="$archive" -- "${sources[@]}"
+			fi
+			;;
+		*.lzma|*.lz)
+			if [ ${#sources[@]} -gt 1 ]
+			then die "unable to compress multiple files in one lzma-archive"
+			else lzma --stdout --force --quiet -- "${sources[@]}" > "$archive"
+			fi
+			;;
+		*.tar.zst|*.tzst)
+			if source_is_tar "${sources[@]}"
+			then zstd --stdout --force --quiet -- "${sources[@]}" > "$archive"
+			else tar --zstd --create --file="$archive" -- "${sources[@]}"
+			fi
+			;;
+		*.zst)
+			if [ ${#sources[@]} -gt 1 ]
+			then die "unable to compress multiple files as one zstd-archive"
+			else zstd --stdout --force --quiet -- "${sources[@]}" > "$archive"
+			fi
+			;;
+		*.zip)
+			zip --quiet --recurse-paths "$archive" -- "${sources[@]}"
+			;;
+		*.7z)
+			7z a -t7z -- "$archive" "${sources[@]}" >/dev/null
+			;;
+
+		* ) die "unsupported archive for '$archive'" ;;
 	esac
 }
+
+die() {
+	printf '%s\n' "$*" >&2
+	exit 1
+}
+
 
 main "$@"
 
diff --git a/_general/dot-local/bin/uarchive b/_general/dot-local/bin/uarchive
--- a/_general/dot-local/bin/uarchive
+++ b/_general/dot-local/bin/uarchive
@@ -1,40 +1,129 @@
 #!/bin/sh
 
-if [ $# -eq 0 ]; then
-	printf 'Usage: %s SOURCE...\n' "$(basename "$0")"
-	exit 1
-fi
+help() {
+	printf 'Usage: %s ARCHIVE\n' "$(basename "$0")"
+	exit "${1:-1}"
+}
 
-for target in "$@"
-do
-	if [ ! -r "$target" ]; then
-		printf "invalid file '%s'\n" "$target" >&2
-		continue
+
+arg_archive=
+
+main() {
+	parse_args "$@"
+
+	if [ ! -r "$arg_archive" ]; then
+		die "invalid file '${arg_archive}'"
 	fi
 
-	# TODO: If archive top level contains more than one file
-	# extract everything into new subdirectory.
-	extract_dir="$(dirname "$target")"
-	if [ ! -w "$extract_dir" ]
-	then
-		printf "missing permissions '%s'\n" "$extract_dir" >&2
-		continue
+	unarchive_one "${arg_archive}"
+}
+
+# 1... args
+parse_args() {
+	if [ $# -ne 1 ]
+	then help
 	fi
 
-	case "$target" in
-		*.tar                   ) tar -xvf "$target"  ;;
-		*.tar.gz|*.tgz          ) tar -zxvf "$target" ;;
-		*.tar.bz2|*.tbz2|*.tbz  ) tar -jxvf "$target" ;;
-		*.tar.xz|*.txz          ) tar -Jxvf "$target" ;;
-		*.tar.zma|*.tlz         ) tar --lzma -xvf "$target" ;;
-		*.gz                    ) gunzip --keep "$target";;
-		*.bz2                   ) bunzip --keep "$target" ;;
-		*.xz                    ) unxz   --keep "$target" ;;
-		*.lzma                  ) unlzma --keep "$target" ;;
-		*.zip                   ) unzip "$target" -d "$extract_dir" ;;
-		*.7z                    ) 7z a -t7z "$target" ;;
+	arg_archive="$1"
+}
 
-		* ) printf "unsupported archive for '%s'\n" "$target" >&2 ;;
+
+
+# TODO: Handle variable dest_dir and dest_name
+unarchive_one() {
+	archive=$1
+	case "$archive" in
+		*.tar)
+			if [ $(tar --list --file="$archive" | wc --lines) -gt 1 ]
+			then mkdir -p "${extract_dir:=${archive%.tar}}"
+			fi
+			tar --extract --file="$archive" --directory="${extract_dir:-.}"
+			;;
+		*.tar.gz|*.tgz)
+			if [ $(tar --gzip --list --file="$archive" | wc --lines) -gt 1 ]
+			then
+				extract_dir="${archive%.tar.gz}"
+				extract_dir="${archive%.tgz}"
+				mkdir -p "$extract_dir"
+			fi
+			tar --gzip --extract --file="$archive" --directory="${extract_dir:-.}"
+			;;
+		*.gz)
+			gunzip --keep "$archive"
+			;;
+		*.tar.bz2|*.tbz2|*.tbz)
+			if [ $(tar --bzip2 --list --file="$archive" | wc --lines) -gt 1 ]
+			then
+				extract_dir="${archive%.tar.bz2}"
+				extract_dir="${archive%.tbz2}"
+				extract_dir="${archive%.tbz}"
+				mkdir -p "$extract_dir"
+			fi
+			tar --bzip2 --extract --file="$archive" --directory="${extract_dir:-.}"
+			;;
+		*.bz2)
+			bunzip --keep "$archive"
+			;;
+		*.tar.xz|*.txz)
+			if [ $(tar --xz --list --file="$archive" | wc --lines) -gt 1 ]
+			then
+				extract_dir="${archive%.tar.xz}"
+				extract_dir="${archive%.txz}"
+				mkdir -p "$extract_dir"
+			fi
+			tar --xz --extract --file="$archive" --directory="${extract_dir:-.}"
+			;;
+		*.xz)
+			unxz --keep "$archive"
+			;;
+		*.tar.lzma|*.tlz)
+			if [ $(tar --lzma --list --file="$archive" | wc --lines) -gt 1 ]
+			then
+				extract_dir="${archive%.tar.lzma}"
+				extract_dir="${archive%.tlz}"
+				mkdir -p "$extract_dir"
+			fi
+			tar --lzma --extract --file="$archive" --directory="${extract_dir:-.}"
+			;;
+		*.lzma|*.lz)
+			unlzma --keep "$archive"
+			;;
+		*.tar.zst|*.tzst)
+			if [ $(tar --lzma --list --file="$archive" | wc --lines) -gt 1 ]
+			then
+				extract_dir="${archive%.tar.zst}"
+				extract_dir="${archive%.tzst}"
+				mkdir -p "$extract_dir"
+			fi
+			tar --zstd --extract --file="$archive" --directory="${extract_dir:-.}"
+			;;
+		*.zst)
+			unzstd --keep --output-dir-mirror "$extract_dir" "$archive"
+			;;
+		*.zip)
+			if [ $(unzip -Z1 "$archive" | wc --lines) -gt 1 ]
+			then mkdir -p "${extract_dir:=${archive%.zip}}"
+			fi
+			unzip -q "$archive" -d "${extract_dir:-.}"
+			;;
+		*.7z)
+			if [ $(7z l "$archive" | tail -n1 | awk '{print $(NF-1)}') -gt 1 ]
+			then extract_dir="${archive%.7z}"
+			fi
+			7z x -o"${extract_dir:-.}" -- "$archive" >/dev/null
+			;;
+
+		* )
+			die "unsupported archive for file '$archive'"
+			;;
 	esac
-done
+}
+
+die() {
+	printf '%s\n' "$*" >&2
+	exit 1
+}
+
+
+main "$@"
 
